[config]

[config.wallpaper]
set = false
command = "false"

[templates.waybar]
input_path = '~/.config/matugen/waybar-colors.css'
output_path = '~/.config/waybar/colors.css'
# waybar automatically reloads files on style change

[templates.sway]
input_path = '~/.config/matugen/sway-colors.conf'
output_path = '~/.config/sway/sway-colors'
post_hook = 'swaymsg "$(grep ^client ~/.config/sway/sway-colors)"'

[templates.mako]
input_path = '~/.config/matugen/mako-colors'
output_path = '~/.config/mako/colors'
post_hook = "makoctl reload"

[templates.bemenu]
input_path = '~/.config/matugen/bemenu.sh'
output_path = '~/.bin/bemenu'
post_hook = "chmod +x ~/.bin/bemenu"

[templates.swaylock]
input_path = '~/.config/matugen/swaylock.conf'
output_path = '~/.config/swaylock/config'
post_hook = "magick ~/.wallpaper -brightness-contrast -10x0 -blur 0x20 ~/.wallpaper_locked"
