#!/bin/bash

set -e

CONFIG_FILE=~/.config/teletextrc

[[ -f $CONFIG_FILE ]] || exit 0
source $CONFIG_FILE

MESSAGE=$(cat -)
SUBJECT=$(awk -F': ' '$1 ~ /Subject/{print $2; exit}' <<< "$MESSAGE")
BODY=$(sed '1,/^$/d' <<< "$MESSAGE")
TELEGRAM_TEXT="${SUBJECT}

${BODY}"

until /usr/bin/curl -G --data-urlencode "chat_id=${CHAT_ID}" --data-urlencode "text=${TELEGRAM_TEXT}" "https://api.telegram.org/bot${API_KEY}/sendMessage"
	do sleep 10
done
