return {
  "nvim-treesitter/nvim-treesitter",
  branch = 'master',
  lazy = false,
  build = ":TSUpdate",
  config = function()
    require("nvim-treesitter.configs").setup {
      auto_install = false,
      sync_install = false,
      ignore_install = {},
      ensure_installed = is_build_system and {
        "bash",
        "c",
        "cpp",
        "css",
        "desktop",
        "dockerfile",
        "dot",
        "editorconfig",
        "fish",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "gnuplot",
        "go",
        "gomod",
        "gosum",
        "gotmpl",
        "html",
        "ini",
        "json",
        "lua",
        "luadoc",
        "markdown",
        "markdown_inline",
        "passwd",
        "proto",
        "python",
        "query",
        "rust",
        "sql",
        "ssh_config",
        "strace",
        "textproto",
        "tmux",
        "toml",
        "typescript",
        "typst",
        "vim",
        "vim",
        "vimdoc",
        "vue",
        "yaml",
      } or {},
      highlight = {
        enable = true,
      }
    }
  end
}
