follow_symlinks = false

[hostname]
ssh_only = false
format = '[@$hostname$ssh_symbol]($style)'
ssh_symbol = '\(ssh\)'

[directory]
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = "git "
